### PR TITLE
Allow specifying custom fetch

### PR DESCRIPTION
**Pull request by bradjones1**
You might want to transform the request going to the server, e.g. to add headers or manipulate the request. This provides a basic setting to specify a custom fetch function.

I'm not necessarily in love with the `typeof fetch` hint but if you're doing this, you should "know what you're doing"?

### CODE REVIEW

**Comment by evert** [comment]
Hey @bradjones1 ,

so it's actually possible with an existing mechanism to do this, and it's the main way we use this with [ketting](https://github.com/badgateway/ketting).

You can do:

```typescript
client.use( (request, next) => {
   return myCustomFetch(request);
}));
```

So given that you didn't discover this, this is probably best treated as a documentation bug ;)

**Comment by evert** [comment]
Ignore my last reply, I'm mixing things up

**Comment by bradjones1** [comment]
@evert Thanks for including my other PR in the latest release... any thoughts on this one as your mind might still be fresh on this library? Thanks!

**Comment by evert** [comment]
Apologies for not having done this yet. I've been dragging my feet because I wanted to use something like this instead:

https://www.npmjs.com/package/fetch-intercept

or re-use the fetch-middleware pattern. The others I could quickly fix and merge, but need to still figure this one out.

**Comment by bradjones1** [comment]
Thanks for the feedback. As for `fetch-intercept`, it seems like that is a global monkeypatch and wouldn't be implemented by the library directly, anyway? In my case, at least, I have a number of clients making requests to my backend over JSON:API, JSON-RPC, and vanilla, unauthenticated fetches for public metadata. So overriding the global is a no-go.

As for the middleware, I'm not quite sure how that would work? The middleware provided by this library references the global `fetch`, so I'm simply suggesting being able to specify the function that's wrapped. Or are you saying that it would be somehow called differently?

**Comment by evert** [comment]
Hey @bradjones1 ,

You're right. I linked the wrong thing. I'm into middleware patterns, but I don't have a good enough framework for this yet. The PR is pretty simple so I'll just merge it and re-release.

**Review by evert — APPROVED** [review]

**Comment by bradjones1** [comment]
Thanks!

**Pull request merged**
